---
micronaut:
  application:
    name: hello
  server:
    port: 8082

---
endpoints:
  health:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false

#---
#mongodb:
#  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
